export const staticDummyProducts = [
  { _id: 'dummy-1',  title: 'Classic Pashmina Shawl', price: 15000, category: 'Shawls', imageUrl: '/Pictures/IMG_3427.JPG.jpeg', inStock: true, description: 'Embrace the warmth with this classic Pashmina shawl, handwoven to perfection by Kashmiri master artisans.' },
  { _id: 'dummy-2',  title: 'Kashmiri Handwoven Stole', price: 18000, category: 'Shawls', imageUrl: '/Pictures/IMG_3428.JPG.jpeg', inStock: true, description: 'Detailed Kashmiri handwoven texture with striking colors.' },
  { _id: 'dummy-3',  title: 'Aari Embroidery Wrap', price: 12000, category: 'Embroidery', imageUrl: '/Pictures/IMG_3429.JPG.jpeg', inStock: true, description: 'Exquisite Aari embroidery work featured gently across the entire wrap.' },
  { _id: 'dummy-4',  title: 'Royal Srinagar Pashmina', price: 25000, category: 'Shawls', imageUrl: '/Pictures/IMG_3430.JPG.jpeg', inStock: true, description: 'A royal quality Pashmina shawl suited for the most elegant occasions.' },
  { _id: 'dummy-5',  title: 'Sozni Needlework Shawl', price: 13500, category: 'Embroidery', imageUrl: '/Pictures/IMG_3431.JPG.jpeg', inStock: true, description: 'Authentic Sozni needlework taking months of precision and dedication.' },
  { _id: 'dummy-6',  title: 'Heritage Wool Wrap', price: 9000, category: 'Shawls', imageUrl: '/Pictures/IMG_3432.JPG.jpeg', inStock: true, description: 'Heritage style wrap providing superior warmth and vintage styling.' },
  { _id: 'dummy-7',  title: 'Premium Winter Stole', price: 16500, category: 'Shawls', imageUrl: '/Pictures/IMG_3433.JPG.jpeg', inStock: true, description: 'The absolute premium choice for deep winter luxury.' },
  { _id: 'dummy-8',  title: 'Kashmiri Artisan Wrap', price: 11000, category: 'Accessories', imageUrl: '/Pictures/IMG_3434.JPG.jpeg', inStock: true, description: 'Versatile wrap doubling as an artisan accessory.' },
  { _id: 'dummy-9',  title: 'Silk Blend Pashmina', price: 21000, category: 'Shawls', imageUrl: '/Pictures/IMG_3435.JPG.jpeg', inStock: true, description: 'Silk blended with raw wool to maintain an elegant shimmer.' },
  { _id: 'dummy-10', title: 'Luxury Bridal Embroidery', price: 28000, category: 'Embroidery', imageUrl: '/Pictures/IMG_3436.JPG.jpeg', inStock: true, description: 'Heavy and dense embroidery ideal for bridal and wedding events.' },
  { _id: 'dummy-11', title: 'Traditional Kani Print', price: 14500, category: 'Shawls', imageUrl: '/Pictures/IMG_3442.JPG.jpeg', inStock: true, description: 'Meticulous traditional Kani motifs woven right into the base.' },
  { _id: 'dummy-12', title: 'Golden Thread Shawl', price: 32000, category: 'Shawls', imageUrl: '/Pictures/IMG_3443.JPG.jpeg', inStock: true, description: 'The grand finale: embedded golden thread detailing across natural wool.' }
];